### ISSUE TITLE
IMPLEMENTACIÓN DE HILOS EN EL PROYECTO DE INGRESO EN EL PÓRTICO DEL INSTITUTO TECNOLÓGICO DE TLAXIACO

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-confident-students#1]
[IMPLEMENTACIÓN DE HILOS EN EL PROYECTO DE INGRESO EN EL PÓRTICO DEL INSTITUTO TECNOLÓGICO DE TLAXIACO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-confident-students/files/15134961/IMPLEMENTACION.DE.HILOS.EN.EL.PROYECTO.DE.INGRESO.EN.EL.PORTICO.DEL.INSTITUTO.TECNOLOGICO.DE.TLAXIACO.pdf)

**Comment by AmeliReyesHernandez** [comment]
De acuerdo con la rubrica tiene 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
